on:
  pull_request:
    types: [closed]
    branches:
      - main
      - master
jobs:
  tag_main:
    # if code merged to 'main/master' br, via PR from 'release' br bearing the 'auto-deploy' label
    if: github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref == 'release' &&
      contains(github.event.pull_request.labels.*.name, 'auto-deploy')
    uses: boromir674/automated-workflows/.github/workflows/go-tag-main.yml@v1.13.1
    with:
      gh_username: ${{ vars.TAG_USER_NAME }}
      gh_email: ${{ vars.TAG_USER_EMAIL }}
      main_branch: ${{ github.event.pull_request.base.ref }}
    secrets:
      # needs Content write to create Tag!
      # needs Actions write to allow other workflows to listen to tag event!
      GH_PAT_ACTION_RW: ${{ secrets.GH_TOKEN_GITOPS_TAG_MAIN }}